// http://www.ettoday.net/events/news-express/epaper.php
export const baseURL = "http://feeds.feedburner.com";
export const URLs = [
  "/ettoday/realtime",
  "/ettoday/news",
  "/ettoday/finance",
  "/ettoday/commentary",
  "/ettoday/global",
  "/ettoday/china",
  "/ettoday/novelty",
  "/ettoday/netsearch",
  "/ettoday/dalemon/",
  "/ettoday/lifestyle",
  "/ettoday/health",
  "/ettoday/society",
  "/ettoday/charity",
  "/ettoday/local",
  "/ettoday/pet",
  "/ettoday/star",
  "/ettoday/gender",
  "/ettoday/sport",
  "/ettoday/travel",
  "/ettoday/consuming",
  "/ettoday/teck3c",
  "/ettoday/game",
  "/ettoday/citizen",
  "/ettoday/master",
  "/ettoday/fortune",
  "/ettoday/video",
  "/ettoday/photo",
];
export const origin = "ettoday";
